SET 'pipeline.name' = 'lakehouse_txn_job_upsert_stream';
SET 'execution.checkpointing.interval' = '10s'; 
SET 'execution.checkpointing.mode' = 'EXACTLY_ONCE';

INSERT INTO awsdatacatalog.rds_master_onlinepayment1.transaction
SELECT 
    TRANID,
    CHANNEL,
    MERCHANTID,
    SUBMER_ID,
    BILLING_NAME,
    BILLING_EMAIL,
    BILLING_MOBILE,
    BILLING_INFO,
    ORDER_ID,
    APP_CODE,
    TRANS_ID,
    BILL_AMT,
    TRANSACTION_RATE,
    CUR_ACTUAL,
    ACTUAL_AMT,
    FRAUD_SCAN,
    FRAUD_SCORE,
    STATUS,
    STATUS_DESCRIPTION,
    MEMO,
    MODIFY_DATE,
    CREATE_DATE,
    TRANKEY,
    STATUS_DESC,
    CHARGEBACK_DATE,
    REFUND_DATE,
    REFUND_AMT,
    HISTORY,
    BIN,
    IP,
    SEC_SCORE,
    SEC_MEMO,
    SEC_CALL,
    SEC_RESULT,
    CCREMINDER_ACK_IP,
    CCREMINDER_ACK,
    FRAUD_DATE,
    RECONCILED,
    BANK_SETTLEMENT_DATE,
    SETID,
    SETTLE_DATE,
    BIN4,
    EXPDATE,
    VCC,
    BIN_NEXIST,
    USER_COUNTRY,
    BANK_COUNTRY,
    CUR_RATES,
    CUR_NUM,
    CUR_AMT,
    DEF_AMT,
    DEF_CUR,
    LOA,
    LOA_NAME,
    POPUPBLOCK,
    ACK_FEEDBACK,
    FRAUD_SCREENING,
    TRANSACTION_COST,
    SUB_TRANSACTION,
    PCODE,
    DUE_TIME,
    TICKET,
    TERMINAL_ID,
    TRACK_LAST_UPDATE,
    L_VERSION,
    RECUR_FLAG,
    PAID_DATE,
    TOKEN_STATUS,
    IS_ESCROW,
    MASTERPASS_TXNID,
    VISACHECKOUT_TXNID,
    DEF_CHANNEL,
    CHANNEL_COST
FROM default_catalog.default_database.lakehouse_txn_table_kafka_source;

RESET 'pipeline.name';
RESET 'execution.checkpointing.interval';
RESET 'execution.checkpointing.mode';